### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by kaivanmehta** [DuanYiqun/Auto-ReID-Fast#2]
what is your_partition and your_node_num? please explain.

**Comment by duanyiqun** [comment]
these two are basic argumentations for srun (multi-nodes with different partition)

**Comment by heerduo** [comment]
when I run this command 
 srun -n 128 --gres 1 -p 0.5 python train_baseline_search_triplet.py --distributed True --config configs/Retrieval_classification_DARTS_distributed_triplet.yaml
(I do not know what are the -n -p and the number of them)

it has this problem:
bash: srun: command not found

how to fix it? Thanks
