### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by heerduo** [DuanYiqun/Auto-ReID-Fast#3]
when I run this command 
 srun -n 128 --gres 1 -p 0.5 python train_baseline_search_triplet.py --distributed True --config configs/Retrieval_classification_DARTS_distributed_triplet.yaml
(I do not know what are the -n -p and the number of them)

it has this problem:
bash: srun: command not found

how to fix it? Thanks

**Comment by kaivanmehta** [comment]
Hey, for that you need to install and set-up slurm. That's for multi-GPU purpose, if you want to run this on single GPU, you don't need to write srun, simply write python [file_name] [arguments]

**Comment by heerduo** [comment]
I use this command :  python train_baseline_search_triplet.py --distributed True --config configs/Retrieval_classification_DARTS_distributed_triplet.yaml

it occurs 
raise KeyError(key) from NONE
KeyError:‘SLURM_PROCID’

**Comment by kaivanmehta** [comment]
If you have not set up slurm, then make sure that --distributed argument is False. Then try!

**Comment by heerduo** [comment]
python train_baseline_search_triplet.py --distributed False --config configs/Retrieval_classification_DARTS_distributed_triplet.yaml

I have changed  --distributed False and use one GPU. It does not work.

**Comment by kaivanmehta** [comment]
Do you face the same error?

**Comment by heerduo** [comment]
Yes

**Comment by kaivanmehta** [comment]
Can you tell me the line number?

**Comment by heerduo** [comment]
I can not find line number in code

**Comment by heerduo** [comment]
if args.distributed
   rank, world_size= 
Though args.distributed is False it also executes rank, world_size

I will delete codes in if args.distributed

**Comment by kaivanmehta** [comment]
Yaa or you can set those variables with some values..

**Comment by heerduo** [comment]
OK

**Comment by duanyiqun** [comment]
> Hey, for that you need to install and set-up slurm. That's for multi-GPU purpose, if you want to run this on single GPU, you don't need to write srun, simply write python [file_name] [arguments]

Thank kaivanmehta very much for your notice. I really write this in a rush. Mostly the code was tested on slurm for distributed training.  You need to set-up slurm to use srun.
